### ISSUE TITLE
Click on title icon opens wrong URL

### ISSUE THREAD

**Issue by schmidHolger** [kenlog/Essential#2]
In case kanboard is started using a port different then port 80, e.g. 8081, a click on the title icon tries to open the wrong URL as it omits the port. 

Line 3 needs to be changed from 
`<a href="<?= $this->url->href('DashboardController', 'show', array(), false, '', t('Dashboard')) ?>">`
to 
`<a href="<?= $this->url->href('DashboardController', 'show', array()) ?>">`

Please check app/Helper/UrlHelper.php - method href()

**Comment by schmidHolger** [comment]
Same issue exists for the Customizer plugin.

**Comment by kenlog** [comment]
Hi @schmidHolger here it is implemented in a standard way as you can compare [here](https://github.com/kanboard/kanboard/blob/8a77a7851ca8552816d52b42897adb4b3807d416/app/Template/header/title.php#L3). Consider opening a new issue in the kanboard repo.
